#!/usr/bin/env python
# coding: utf-8

# Part 1 Script Packages
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# Part 2 Script Packages
import os
import time
import pathlib
from pathlib import Path
import pandas as pd

# Part 3 Script Packages
import smtplib
import datetime as dt
import time
import email
import ssl
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
